### ISSUE TITLE
作业加载失败

### ISSUE THREAD

**Issue by jerry184533** [MaaAssistantArknights/maa-copilot-frontend#86] opened 2022-11-16 07:22 UTC
![image](https://user-images.githubusercontent.com/118339204/202113223-b7985f86-1408-4ea7-b211-fc3c652f80b0.png)
前几天还没问题

**Comment by guansss** [comment] 2022-11-16 09:10
Duplicate of #81

**Closed by guansss** 2022-11-16 09:10 UTC
