### ISSUE TITLE
网站崩了

### ISSUE THREAD

**Issue by mosquito-777** [MaaAssistantArknights/maa-copilot-frontend#105] opened 2022-12-18 04:26 UTC

**Comment by mosquito-777** [comment] 2022-12-18 04:27
![N 9L2``UJJ~{YF K$2XPWNB](https://user-images.githubusercontent.com/112480492/208281478-1c3e7168-ec23-4afe-a644-c5c319435edc.png)

**Comment by guansss** [comment] 2022-12-18 09:53
Duplicate of #104

**Closed by guansss** 2022-12-18 09:53 UTC
